#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-hisiv400-linux-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H  -DL_ENDIAN -DTERMIO -O3 -Wall"
  #define PLATFORM "linux-x86_64"
  #define DATE "Sun Oct 21 16:09:20 CST 2018"
#endif
